# Generated by Django 2.2.28 on 2024-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
