# Generated by Django 2.2.28 on 2024-11-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
