# Generated by Django 2.2.28 on 2024-11-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0005_remove_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(default='預設課程名稱'),
            preserve_default=False,
        ),
    ]
